mysql:
  dns: root:root@tcp(127.0.0.1:3306)/heyChat?charset=utf8mb4&parseTime=True&loc=Local
app:
  this is app
redis:
  addr: "192.168.122.206:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30